### 3. Relu
- By Using of Sigmoid And Tanh function there is vanishing gradient problem occure so the convergence rate slow down.
- To overcome slighlty we use Relu Function. it not totally overcome this problem but here the convergence rate is faster than sigmoid and tanh.
- Value Range :- [0, inf)
- Its Nature non-linear, which means we can easily backpropagate the errors and have multiple layers of neurons being activated by the ReLU function.
<img src="20.png" style="height:350px;">

##### Point:
1. <u>Vanishing Gradient Problem</u> occure due to multiple number of derivative.
2. As sigmoid derivative 0 to 0.25 so by multiple by this sigmoid derivative the result might vanishing gradient as number of hidden layer increase.
3. But in Relu here its derivative 0 to 1 so here no problem of any vanishing gradient problem as its derivative cant be 0.2,0.3 like. 
4. But as its derivative can be 0 so here a problem aries that called Dead_Activation

<b>Uses :-</b> ReLu is less computationally expensive than tanh and sigmoid because it involves simpler mathematical operations. At a time only a few neurons are activated making the network sparse making it efficient and easy for computation.

### What is Dead_Activation ?
- When Derivative equal to 0 in Relu Then New Weight = Old Weight : <img src='21.png'>

which is not good for any model.Here Weight Cant be update. it occure when value of z is negative.This state called Dead Activation state. to overcome this we use Leaky Relu.
<img src="22.png">
- See here no updation happen the value remain same and ‘nan’ for validation loss is an unexpected very large or very small number. This is dead activation state to overcome this we use leaky relu

### mplementing the ReLu function in NumPy is very straight forward:

In [1]:
import numpy as np
mmatrix= np.array([[1,2,3],[4,5,6]])
print(mmatrix)

[[1 2 3]
 [4 5 6]]


In [2]:
#ReLu function
def relu(X):
   return np.maximum(0,X)
#Example with mmatrix defined above
relu(mmatrix)

array([[1, 2, 3],
       [4, 5, 6]])

## 4. Leaky Relu
- Leaky ReLU is an improved version of the ReLU function.
- ReLU function, the gradient is 0 for x < 0(-ve), which made the neurons die for activations in that region.
- Leaky ReLU is defined to address this problem. Instead of defining the Relu function as 0 for x less than 0, we define it as a small linear component of x. 
- Leaky ReLUs are one attempt to fix the Dying ReLU problem. Instead of the function being zero when x < 0, a leaky ReLU will instead have a small negative slope (of 0.01, or so). That is, the function computes:
<img src="23.png">
<img src="24.png"  style="height:350px">

In [3]:
### Here are two approaches to implement leaky_relu:
import numpy as np                                                 

x = np.random.normal(size=[1, 5])

# first approach                           
leaky_way1 = np.where(x > 0, x, x * 0.01)                          

# second approach                                                                   
y1 = ((x > 0) * x)                                                 
y2 = ((x <= 0) * x * 0.01)                                         
leaky_way2 = y1 + y2  

print(leaky_way1)
print(leaky_way2)

[[ 0.87916693  0.18566813 -0.00252958  0.85384231 -0.01014912]]
[[ 0.87916693  0.18566813 -0.00252958  0.85384231 -0.01014912]]


### Sigmoid,Tanh,Relu,Leaky Relu

<img src="26.png">